---
name: Python package

on:
  push:
    branches: [master, develop, "feature/*"]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3     # kept

    - name: Set up Python
      uses: actions/setup-python@v4 # minor version bump
      with:
        python-version: ${{ matrix.python-version }}

    # ------------- uv replaces Poetry here -------------
    - name: Cache uv wheels
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
        restore-keys: uv-${{ runner.os }}-

    - name: Install uv & project deps
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync
    # ----------------------------------------------------

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run Pre-commit Hooks
      run: pre-commit run --config .pre-commit-config.yaml --all-files

    - name: Run Linting and Formatting Checks with Ruff
      run: |
        ruff check --fix --unsafe-fixes
        ruff format

    - name: Run Tests with Coverage
      continue-on-error: true
      run: |
        pytest --cov=src --cov-fail-under=85 --cov-report xml

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Build MkDocs
      run: mkdocs build

    - name: Deploy MkDocs
      run: mkdocs gh-deploy --force
